version: '1.0'

services:
  gateway:
    build: ./
    container_name: 'mission-gateway'
    ports:
      - 80:80
    networks:
      - mission
    volumes:
      - ./assets:/app/assets
    environment:
      AUTHORIZATION_URL: http://auth:8081/auth/check
      ROUTES_CONFIG: file:assets/routes.yml
networks:
  mission:
    driver: bridge