version: '1.0'

services:
  gateway:
    build: ./
    container_name: 'mission-gateway'
    ports:
      - 80:80
    networks:
      - mission
    volumes:
      - ./assets:/app/assets
networks:
  mission:
    driver: bridge