spring:
  application:
    name: gateway
  config:
    import: ${ROUTES_CONFIG}
authorization:
  microservice:
    url: ${AUTHORIZATION_URL}
server:
  port: 80
logging:
  level:
    reactor:
      netty:
        http:
          client: DEBUG