spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: auth
          uri: http://auth:8081/
          predicates:
            - Path=/auth/**
          metadata:
            auth_type: NOTHING
server:
  port: 80
authorization:
  microservice:
    url: http://auth:8081/auth/check
