spring:
  cloud:
    gateway:
      routes:
        - id: auth
          uri: http://localhost:8081/
          predicates:
            - Path=/auth/**
          metadata:
            auth_type: NOTHING
        - id: profile_public
          uri: http://localhost:8082/
          predicates:
            - Path=/profile/*
          metadata:
            auth_type: LIGHT
        - id: profile_private
          uri: http://localhost:8082/
          predicates:
            - Path=/profile/private/*
          metadata:
            auth_type: LIGHT
            allowing_roles:
              - ADMIN