spring:
  cloud:
    gateway:
      routes:
        - id: auth
          uri: http://auth:8081/
          predicates:
            - Path=/auth/*
          metadata:
            auth_type: NOTHING
        - id: identify
          uri: http://identify/
          predicates:
            - Path=/private/id/mission/identify
          metadata:
            auth_type: EXTERNAL_ID_PROVIDER
        - id: profile_public
          uri: http://profile/
          predicates:
            - Path=/profile/*
          metadata:
            auth_type: LIGHT
        - id: profile_private
          uri: http://profile/
          predicates:
            - Path=/profile/private/*
          metadata:
            auth_type: LIGHT
        - id: project_admin
          uri: http://project:80/
          predicates:
            - Path=/project/admin/*
          metadata:
            auth_type: LIGHT
            allowing_roles:
              - ADMIN
        - id: project_manager
          uri: http://project:80/
          predicates:
            - Path=/project/manager/*
          metadata:
            auth_type: LIGHT
            allowing_roles:
              - MANAGER
        - id: project_private
          uri: http://project:80/
          predicates:
            - Path=/project/private/**
          metadata:
            auth_type: LIGHT
        - id: project_public
          uri: http://project:80/
          predicates:
            - Path=/project/*
          metadata:
            auth_type: NOTHING
        - id: set_roles
          uri: http://auth:8081/
          predicates:
            - Path=/roles/set_role
          metadata:
            auth_type: HUGE
            allowing_roles:
              - ADMIN
        - id: profile_search_manager
          uri: http://profile
          predicates:
              - Path=/profile/manager/search/*
          metadata:
              auth_type: HUGE
              allowing_roles:
                  - MANAGER