spring:
  cloud:
    gateway:
      routes:
        - id: auth
          uri: http://auth:8081/
          predicates:
            - Path=/auth/**
          metadata:
            auth_type: NOTHING
        - id: profile_public
          uri: http://profile:8082/
          predicates:
            - Path=/profile/*
          metadata:
            auth_type: LIGHT
        - id: profile_private
          uri: http://profile:8082/
          predicates:
            - Path=/profile/private/*
          metadata:
            auth_type: LIGHT
            allowing_roles:
              - ADMIN
        - id: project_admin
          uri: http://project:80/
          predicates:
            - Path=/project/private/admin/*
          metadata:
            auth_type: LIGHT
            allowing_roles:
              - ADMIN
        - id: project_private
          uri: http://project:80/
          predicates:
            - Path=/project/private/admin/*
          metadata:
            auth_type: LIGHT
            allowing_roles:
              - ADMIN